spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1172093Nik
  flyway:
    baseline-on-migrate: true
